"""add_anio_cartera

Revision ID: c8d2b0e4a77a
Revises: 8a5c8c2f0af7
Create Date: 2026-05-26 08:42:31.985161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c8d2b0e4a77a'
down_revision: Union[str, None] = '8a5c8c2f0af7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cartera_servicios', sa.Column('anio', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_cartera_servicios_anio'), 'cartera_servicios', ['anio'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cartera_servicios_anio'), table_name='cartera_servicios')
    op.drop_column('cartera_servicios', 'anio')
    # ### end Alembic commands ###
